services:
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - /var/chirpstack/ca-certificate.crt:/var/chirpstack/ca-certificate.crt
    env_file:
      - ../../var/chirpstack/chirpstack.env 
    ports:
      - "8080:8080"

  # chirpstack-gateway-bridge:
  #   image: chirpstack/chirpstack-gateway-bridge:4
  #   restart: unless-stopped
  #   ports:
  #     - "1700:1700/udp"
  #   volumes:
  #     - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
  #   environment:
  #     - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
  #     - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
  #     - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/command/#
  
  # TODO: implement basicstation
  # chirpstack-gateway-bridge-basicstation:
  #   image: chirpstack/chirpstack-gateway-bridge:4
  #   restart: unless-stopped
  #   command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge